export interface Collection {
  id: string;
  slug: string;
  title: string;
  description: string;
  emoji: string;
  color: string; // tailwind gradient from color
  resourceSlugs: string[];
}

export const COLLECTIONS: Collection[] = [
  {
    id: "getting-started-claude",
    slug: "getting-started-claude",
    title: "Getting Started with Claude",
    description: "The easiest on-ramps for new Claude Code users. Beginner-friendly MCPs, essential setups, and foundational tricks to get productive fast.",
    emoji: "🚀",
    color: "violet",
    resourceSlugs: [
      "mcp-postgres",
      "mcp-github",
      "mcp-filesystem",
      "setup-minimal-coding",
      "trick-extended-thinking",
      "trick-custom-commands",
      "hook-auto-format",
    ],
  },
  {
    id: "data-pipeline-essentials",
    slug: "data-pipeline-essentials",
    title: "Data Pipeline Essentials",
    description: "Core data engineering tools: dbt, Airflow, Kafka, and pipeline agents. Everything you need to build, orchestrate, and monitor production pipelines.",
    emoji: "🔧",
    color: "emerald",
    resourceSlugs: [
      "dbt-cloud-mcp",
      "airflow-mcp",
      "kafka-mcp",
      "agent-data-pipeline",
      "pipeline-monitor-agent",
      "generate-dag-skill",
      "data-engineer-setup",
    ],
  },
  {
    id: "sql-power-pack",
    slug: "sql-power-pack",
    title: "SQL Power Pack",
    description: "Everything SQL — from natural language to optimized queries. Covers Snowflake, BigQuery, DuckDB, Redshift, plus the best SQL prompts and skills.",
    emoji: "🗄️",
    color: "cyan",
    resourceSlugs: [
      "snowflake-mcp",
      "bigquery-mcp",
      "duckdb-mcp",
      "nl-to-sql-prompt",
      "prompt-sql-optimizer",
      "sql-optimize-skill",
      "explain-sql-skill",
      "sql-review-agent",
    ],
  },
  {
    id: "ml-engineer-toolkit",
    slug: "ml-engineer-toolkit",
    title: "ML Engineer's Toolkit",
    description: "ML-focused agents, setups, and architectures. From feature engineering with Spark to experiment tracking and RAG pipeline design.",
    emoji: "🧠",
    color: "blue",
    resourceSlugs: [
      "spark-mcp",
      "delta-lake-mcp",
      "databricks-mcp",
      "arch-rag-pipeline",
      "prompt-ml-experiment",
      "ml-experiment-prompt",
      "anomaly-detection-agent",
    ],
  },
  {
    id: "open-source-champions",
    slug: "open-source-champions",
    title: "Open Source Champions",
    description: "The highest-starred resources in the registry. Battle-tested by thousands of engineers and data professionals worldwide.",
    emoji: "⭐",
    color: "yellow",
    resourceSlugs: [
      "duckdb-mcp",
      "snowflake-mcp",
      "nl-to-sql-prompt",
      "trick-extended-thinking",
      "pandas-ai-trick",
      "trick-prompt-caching",
      "bigquery-mcp",
      "databricks-mcp",
    ],
  },
  {
    id: "productivity-boosters",
    slug: "productivity-boosters",
    title: "Productivity Boosters",
    description: "Prompts, tricks, and skills that speed up your daily data work. Designed for engineers who want to move faster without cutting corners.",
    emoji: "⚡",
    color: "orange",
    resourceSlugs: [
      "trick-extended-thinking",
      "trick-prompt-caching",
      "trick-ci-claude",
      "trick-custom-commands",
      "hook-auto-format",
      "hook-test-runner",
      "skill-ship",
      "pandas-ai-trick",
    ],
  },
  {
    id: "real-time-data-stack",
    slug: "real-time-data-stack",
    title: "Real-time Data Stack",
    description: "Streaming and real-time resources for event-driven data systems. Kafka, Flink, ClickHouse, and the agents to keep them running smoothly.",
    emoji: "🌊",
    color: "teal",
    resourceSlugs: [
      "kafka-mcp",
      "apache-flink-mcp",
      "clickhouse-mcp",
      "prefect-mcp",
      "pipeline-monitor-agent",
      "schema-drift-agent",
      "arch-event-driven",
    ],
  },
  {
    id: "data-quality-reliability",
    slug: "data-quality-reliability",
    title: "Data Quality & Reliability",
    description: "Tools, agents, and hooks for validating data, catching anomalies, and ensuring your pipelines deliver trustworthy data every time.",
    emoji: "✅",
    color: "green",
    resourceSlugs: [
      "great-expectations-mcp",
      "soda-mcp",
      "anomaly-detection-agent",
      "schema-drift-agent",
      "data-quality-skill",
      "data-validation-hook",
      "incident-rca-prompt",
    ],
  },
];
