import type { Resource } from "./types";

export const resources: Resource[] = [
  // ── MCPs ─────────────────────────────────────────────────────────────────
  {
    id: "mcp-postgres",
    slug: "mcp-postgres",
    name: "PostgreSQL MCP",
    tagline: "Query and manage PostgreSQL databases with natural language",
    description:
      "Full PostgreSQL access for Claude. Write SQL, inspect schemas, run migrations, and explore your data — all through natural language. Supports multiple connections and read-only mode for safety.",
    type: "mcp",
    tags: ["database", "sql", "postgresql", "data-engineering"],
    author: "Anthropic",
    authorUrl: "https://github.com/anthropics",
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/postgres",
    installCommand: "npx @modelcontextprotocol/server-postgres postgresql://localhost/mydb",
    stars: 2100,
    forks: 340,
    lastUpdated: "2 days ago",
    complexity: "beginner",
    useCases: ["data-engineering", "python"],
    featured: true,
    trending: true,
    hot: true,
    verified: true,
    weeklyViews: 4800,
  },
  {
    id: "mcp-github",
    slug: "mcp-github",
    name: "GitHub MCP",
    tagline: "Full GitHub API — PRs, issues, code search, repo management",
    description:
      "Interact with GitHub from Claude. Create and review pull requests, manage issues, search code, inspect commits, and manage repository settings. The most popular MCP for engineering workflows.",
    type: "mcp",
    tags: ["github", "git", "data-ops", "collaboration"],
    author: "Anthropic",
    authorUrl: "https://github.com/anthropics",
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/github",
    installCommand: "npx @modelcontextprotocol/server-github",
    stars: 3400,
    forks: 620,
    lastUpdated: "1 day ago",
    complexity: "beginner",
    useCases: ["python", "data-ops"],
    featured: true,
    trending: true,
    hot: true,
    verified: true,
    weeklyViews: 6200,
  },
  {
    id: "mcp-filesystem",
    slug: "mcp-filesystem",
    name: "Filesystem MCP",
    tagline: "Read, write, and manage local files and directories",
    description:
      "Give Claude access to your local filesystem. Read files, write code, manage directories, and navigate your project structure. The essential MCP for any local development setup.",
    type: "mcp",
    tags: ["filesystem", "files", "local", "essential"],
    author: "Anthropic",
    authorUrl: "https://github.com/anthropics",
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
    installCommand: "npx @modelcontextprotocol/server-filesystem /path/to/dir",
    stars: 2900,
    forks: 490,
    lastUpdated: "3 days ago",
    complexity: "beginner",
    useCases: ["python", "productivity"],
    featured: true,
    trending: false,
    hot: false,
    verified: true,
    weeklyViews: 5100,
  },
  {
    id: "mcp-sqlite",
    slug: "mcp-sqlite",
    name: "SQLite MCP",
    tagline: "Lightweight local database access — perfect for prototyping",
    description:
      "Query and manipulate SQLite databases directly from Claude. Ideal for local development, rapid prototyping, and data exploration without a full database server.",
    type: "mcp",
    tags: ["sqlite", "database", "local", "sql"],
    author: "Anthropic",
    authorUrl: "https://github.com/anthropics",
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite",
    installCommand: "npx @modelcontextprotocol/server-sqlite /path/to/db.sqlite",
    stars: 1800,
    forks: 280,
    lastUpdated: "4 days ago",
    complexity: "beginner",
    useCases: ["data-engineering", "python"],
    featured: false,
    trending: false,
    hot: false,
    verified: true,
    weeklyViews: 3200,
  },
  {
    id: "mcp-brave-search",
    slug: "mcp-brave-search",
    name: "Brave Search MCP",
    tagline: "Real-time web search without tracking",
    description:
      "Give Claude internet access via Brave's privacy-respecting search API. Find current information, research topics, validate facts, and answer questions about recent events.",
    type: "mcp",
    tags: ["search", "web", "data-science", "real-time"],
    author: "Brave",
    authorUrl: "https://github.com/brave",
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search",
    installCommand: "npx @modelcontextprotocol/server-brave-search",
    stars: 1200,
    forks: 190,
    lastUpdated: "5 days ago",
    complexity: "beginner",
    useCases: ["data-science", "productivity"],
    featured: false,
    trending: true,
    hot: false,
    verified: true,
    weeklyViews: 3900,
  },
  {
    id: "mcp-supabase",
    slug: "mcp-supabase",
    name: "Supabase MCP",
    tagline: "Full Supabase control — tables, auth, storage, edge functions",
    description:
      "Complete Supabase integration for Claude. Manage tables, RLS policies, run SQL, handle auth users, browse storage, and invoke edge functions — all from natural language.",
    type: "mcp",
    tags: ["supabase", "database", "backend", "postgres"],
    author: "Supabase",
    authorUrl: "https://github.com/supabase",
    githubUrl: "https://github.com/supabase-community/supabase-mcp",
    installCommand: "npx @supabase/mcp-server-supabase",
    stars: 2200,
    forks: 370,
    lastUpdated: "1 day ago",
    complexity: "intermediate",
    useCases: ["python", "data-engineering"],
    featured: true,
    trending: true,
    hot: true,
    verified: true,
    weeklyViews: 4400,
  },
  {
    id: "mcp-vercel",
    slug: "mcp-vercel",
    name: "Vercel MCP",
    tagline: "Deploy, manage projects, view logs — ship directly from Claude",
    description:
      "Complete Vercel control from Claude. Deploy projects, manage environment variables, inspect build logs, view runtime errors, manage domains, and monitor deployments.",
    type: "mcp",
    tags: ["vercel", "deployment", "hosting", "data-ops"],
    author: "Vercel",
    authorUrl: "https://github.com/vercel",
    githubUrl: "https://github.com/vercel/mcp-server-vercel",
    installCommand: "npx @vercel/mcp-server",
    stars: 1500,
    forks: 240,
    lastUpdated: "2 days ago",
    complexity: "beginner",
    useCases: ["data-ops", "python"],
    featured: false,
    trending: true,
    hot: true,
    verified: true,
    weeklyViews: 3600,
  },
  {
    id: "mcp-slack",
    slug: "mcp-slack",
    name: "Slack MCP",
    tagline: "Send messages, search history, manage channels",
    description:
      "Integrate Claude into your Slack workflow. Send and search messages, list channels, manage notifications, and surface important conversations — without leaving your terminal.",
    type: "mcp",
    tags: ["slack", "messaging", "team", "communication"],
    author: "Community",
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/slack",
    installCommand: "npx @modelcontextprotocol/server-slack",
    stars: 890,
    forks: 140,
    lastUpdated: "6 days ago",
    complexity: "beginner",
    useCases: ["productivity"],
    featured: false,
    trending: false,
    hot: false,
    verified: true,
    weeklyViews: 2100,
  },
  {
    id: "mcp-notion",
    slug: "mcp-notion",
    name: "Notion MCP",
    tagline: "Read and write Notion pages, databases, and blocks",
    description:
      "Your second brain, now AI-accessible. Query and update Notion databases, create pages, manage blocks, and integrate your knowledge base into Claude workflows.",
    type: "mcp",
    tags: ["notion", "notes", "knowledge", "productivity"],
    author: "Community",
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/notion",
    installCommand: "npx @modelcontextprotocol/server-notion",
    stars: 1100,
    forks: 180,
    lastUpdated: "1 week ago",
    complexity: "beginner",
    useCases: ["productivity", "data-science"],
    featured: false,
    trending: false,
    hot: false,
    verified: true,
    weeklyViews: 2400,
  },
  {
    id: "mcp-linear",
    slug: "mcp-linear",
    name: "Linear MCP",
    tagline: "Create issues, manage sprints, view roadmaps",
    description:
      "Engineering project management from Claude. Create and update issues, manage sprint backlogs, view roadmaps, and track project progress — the dev-first PM tool with Claude.",
    type: "mcp",
    tags: ["linear", "project-management", "issues", "sprints"],
    author: "Community",
    githubUrl: "https://github.com/linear/linear-mcp",
    stars: 760,
    forks: 120,
    lastUpdated: "1 week ago",
    complexity: "beginner",
    useCases: ["python", "productivity"],
    featured: false,
    trending: false,
    hot: false,
    verified: false,
    weeklyViews: 1800,
  },
  {
    id: "mcp-stripe",
    slug: "mcp-stripe",
    name: "Stripe MCP",
    tagline: "Customers, payments, subscriptions — payment ops from Claude",
    description:
      "Manage your Stripe account from Claude. Query customers, review payments, handle subscriptions, inspect webhook events, and run payment operations without the dashboard.",
    type: "mcp",
    tags: ["stripe", "payments", "billing", "api"],
    author: "Community",
    githubUrl: "https://github.com/stripe/agent-toolkit",
    stars: 980,
    forks: 160,
    lastUpdated: "5 days ago",
    complexity: "intermediate",
    useCases: ["python"],
    featured: false,
    trending: true,
    hot: false,
    verified: true,
    weeklyViews: 2700,
  },
  {
    id: "mcp-puppeteer",
    slug: "mcp-puppeteer",
    name: "Puppeteer MCP",
    tagline: "Browser automation — navigate, scrape, screenshot, fill forms",
    description:
      "Full headless browser control for Claude. Navigate web pages, extract structured data, take screenshots, fill and submit forms, and automate browser workflows.",
    type: "mcp",
    tags: ["puppeteer", "browser", "scraping", "automation"],
    author: "Community",
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer",
    installCommand: "npx @modelcontextprotocol/server-puppeteer",
    stars: 1700,
    forks: 280,
    lastUpdated: "3 days ago",
    complexity: "intermediate",
    useCases: ["python", "data-science"],
    featured: false,
    trending: true,
    hot: true,
    verified: true,
    weeklyViews: 3300,
  },
  {
    id: "mcp-docker",
    slug: "mcp-docker",
    name: "Docker MCP",
    tagline: "Container management, image building, compose operations",
    description:
      "Manage Docker containers and images from Claude. Build images, manage containers, run compose operations, inspect logs, and handle your container infrastructure through natural language.",
    type: "mcp",
    tags: ["docker", "containers", "data-ops", "infrastructure"],
    author: "Community",
    githubUrl: "https://github.com/ckreiling/mcp-server-docker",
    stars: 1300,
    forks: 210,
    lastUpdated: "4 days ago",
    complexity: "intermediate",
    useCases: ["data-ops"],
    featured: false,
    trending: false,
    hot: false,
    verified: false,
    weeklyViews: 2600,
  },
  {
    id: "mcp-google-drive",
    slug: "mcp-google-drive",
    name: "Google Drive MCP",
    tagline: "Read and write Google Docs, Sheets, and Drive files",
    description:
      "Access your Google Drive from Claude. Read and write Google Docs, query Sheets, list files, and manage your cloud documents — full Drive access from your terminal.",
    type: "mcp",
    tags: ["google", "drive", "docs", "sheets"],
    author: "Community",
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/gdrive",
    stars: 720,
    forks: 110,
    lastUpdated: "1 week ago",
    complexity: "beginner",
    useCases: ["productivity", "productivity"],
    featured: false,
    trending: false,
    hot: false,
    verified: true,
    weeklyViews: 1700,
  },
  {
    id: "mcp-aws-s3",
    slug: "mcp-aws-s3",
    name: "AWS S3 MCP",
    tagline: "Object storage — upload, download, list, manage buckets",
    description:
      "Full AWS S3 access from Claude. Upload and download files, list buckets and objects, manage permissions, configure lifecycle rules, and automate your S3 workflows.",
    type: "mcp",
    tags: ["aws", "s3", "storage", "cloud"],
    author: "Community",
    githubUrl: "https://github.com/aws/aws-mcp",
    stars: 920,
    forks: 150,
    lastUpdated: "5 days ago",
    complexity: "intermediate",
    useCases: ["data-ops", "data-engineering"],
    featured: false,
    trending: false,
    hot: false,
    verified: false,
    weeklyViews: 2200,
  },
  {
    id: "mcp-mongodb",
    slug: "mcp-mongodb",
    name: "MongoDB MCP",
    tagline: "Document queries, aggregations, and collection management",
    description:
      "Query and manage MongoDB databases from Claude. Write aggregation pipelines, inspect documents, manage indexes, and explore your collections — Mongo without the GUI.",
    type: "mcp",
    tags: ["mongodb", "nosql", "database", "documents"],
    author: "Community",
    githubUrl: "https://github.com/mongodb-developer/mcp-mongodb",
    stars: 840,
    forks: 130,
    lastUpdated: "6 days ago",
    complexity: "intermediate",
    useCases: ["data-engineering", "python"],
    featured: false,
    trending: false,
    hot: false,
    verified: false,
    weeklyViews: 1900,
  },
  {
    id: "mcp-gmail",
    slug: "mcp-gmail",
    name: "Gmail MCP",
    tagline: "Read, search, draft, and send emails from Claude",
    description:
      "Full Gmail access from Claude. Search your inbox, read and draft emails, manage labels, send messages, and handle email workflows — all through natural language commands.",
    type: "mcp",
    tags: ["gmail", "email", "google", "productivity"],
    author: "Community",
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/gmail",
    stars: 810,
    forks: 130,
    lastUpdated: "1 week ago",
    complexity: "beginner",
    useCases: ["productivity"],
    featured: false,
    trending: false,
    hot: false,
    verified: false,
    weeklyViews: 1900,
  },
  {
    id: "mcp-railway",
    slug: "mcp-railway",
    name: "Railway MCP",
    tagline: "Deploy and manage Railway services, databases, and environments",
    description:
      "Manage your Railway infrastructure from Claude. Deploy services, provision databases, manage environment variables, view logs, scale services, and monitor your applications.",
    type: "mcp",
    tags: ["railway", "deployment", "hosting", "data-ops"],
    author: "Railway",
    authorUrl: "https://github.com/railwayapp",
    githubUrl: "https://github.com/railwayapp/mcp-railway",
    stars: 640,
    forks: 95,
    lastUpdated: "3 days ago",
    complexity: "beginner",
    useCases: ["data-ops"],
    featured: false,
    trending: true,
    hot: false,
    verified: true,
    weeklyViews: 1600,
  },

  // ── Skills ────────────────────────────────────────────────────────────────
  {
    id: "skill-ship",
    slug: "skill-ship",
    name: "/ship",
    tagline: "Full ship workflow: tests, review, changelog, PR creation",
    description:
      "The complete ship workflow. Detects and merges base branch, runs tests, reviews diff, bumps VERSION, updates CHANGELOG, commits, pushes, creates PR. Invoke when code is ready to land.",
    type: "skill",
    tags: ["git", "deployment", "workflow", "pr"],
    author: "garrytan / gstack",
    authorUrl: "https://github.com/garrytan",
    githubUrl: "https://github.com/garrytan/gstack",
    stars: 1200,
    forks: 190,
    lastUpdated: "2 days ago",
    complexity: "beginner",
    useCases: ["python", "data-ops"],
    featured: true,
    trending: true,
    hot: true,
    verified: true,
    weeklyViews: 5200,
  },
  {
    id: "skill-qa",
    slug: "skill-qa",
    name: "/qa",
    tagline: "Systematically test a web app, find bugs, fix and re-verify",
    description:
      "Full QA workflow: navigate pages, find bugs, fix each one in source code, commit atomically, re-verify. Produces before/after health scores and a ship-readiness summary.",
    type: "skill",
    tags: ["testing", "qa", "bugs", "browser"],
    author: "garrytan / gstack",
    authorUrl: "https://github.com/garrytan",
    githubUrl: "https://github.com/garrytan/gstack",
    stars: 980,
    forks: 160,
    lastUpdated: "3 days ago",
    complexity: "intermediate",
    useCases: ["python"],
    featured: false,
    trending: true,
    hot: false,
    verified: true,
    weeklyViews: 3800,
  },
  {
    id: "skill-investigate",
    slug: "skill-investigate",
    name: "/investigate",
    tagline: "Systematic debugging: investigate → analyze → fix with root cause",
    description:
      "Iron Law: no fixes without root cause. Four phases: investigate, analyze, hypothesize, implement. Proactively invoked on errors, 500s, stack traces, and unexpected behavior.",
    type: "skill",
    tags: ["debugging", "bugs", "root-cause", "analysis"],
    author: "garrytan / gstack",
    authorUrl: "https://github.com/garrytan",
    githubUrl: "https://github.com/garrytan/gstack",
    stars: 870,
    forks: 140,
    lastUpdated: "4 days ago",
    complexity: "intermediate",
    useCases: ["python"],
    featured: false,
    trending: false,
    hot: false,
    verified: true,
    weeklyViews: 3100,
  },
  {
    id: "skill-review-code",
    slug: "skill-review-code",
    name: "/review",
    tagline: "Pre-landing code review: bugs, security, SQL safety, side effects",
    description:
      "Critically review all uncommitted code changes before production. Identifies bugs, security issues, SQL injection risks, LLM trust boundary violations, and performance problems.",
    type: "skill",
    tags: ["code-review", "data-ops", "quality", "pr"],
    author: "garrytan / gstack",
    authorUrl: "https://github.com/garrytan",
    githubUrl: "https://github.com/garrytan/gstack",
    stars: 1100,
    forks: 175,
    lastUpdated: "2 days ago",
    complexity: "beginner",
    useCases: ["python", "data-ops"],
    featured: true,
    trending: true,
    hot: false,
    verified: true,
    weeklyViews: 4600,
  },
  {
    id: "skill-office-hours",
    slug: "skill-office-hours",
    name: "/office-hours",
    tagline: "YC Office Hours in your terminal — startup mode or builder mode",
    description:
      "Two modes: Startup (6 forcing questions about demand, wedge, and future-fit) or Builder (design partner for side projects). Produces a design document and founder guidance.",
    type: "skill",
    tags: ["startup", "product", "brainstorming", "yc"],
    author: "garrytan / gstack",
    authorUrl: "https://github.com/garrytan",
    githubUrl: "https://github.com/garrytan/gstack",
    stars: 760,
    forks: 120,
    lastUpdated: "5 days ago",
    complexity: "beginner",
    useCases: ["productivity", "data-science"],
    featured: false,
    trending: false,
    hot: false,
    verified: true,
    weeklyViews: 2800,
  },
  {
    id: "skill-design-review",
    slug: "skill-design-review",
    name: "/design-review",
    tagline: "Visual QA: spacing, hierarchy, AI slop, slow interactions",
    description:
      "Designer's eye QA. Finds visual inconsistencies, spacing issues, hierarchy problems, and AI slop patterns. Fixes them in source code, commits each atomically, re-verifies with screenshots.",
    type: "skill",
    tags: ["design", "ui", "ux", "visual"],
    author: "garrytan / gstack",
    authorUrl: "https://github.com/garrytan",
    githubUrl: "https://github.com/garrytan/gstack",
    stars: 820,
    forks: 130,
    lastUpdated: "5 days ago",
    complexity: "beginner",
    useCases: ["python"],
    featured: false,
    trending: true,
    hot: false,
    verified: true,
    weeklyViews: 3200,
  },
  {
    id: "skill-research-deep",
    slug: "skill-research-deep",
    name: "/research-deep",
    tagline: "Karpathy LLM Wiki pattern: vault research + cross-page rewrites",
    description:
      "Deep research using the Karpathy LLM Wiki pattern. Reads existing vault pages first, then does external research, then rewrites affected pages. Every ingest rewrites 5-15 pages.",
    type: "skill",
    tags: ["data-science", "notes", "obsidian", "knowledge"],
    author: "garrytan / gstack",
    authorUrl: "https://github.com/garrytan",
    githubUrl: "https://github.com/garrytan/gstack",
    stars: 910,
    forks: 145,
    lastUpdated: "4 days ago",
    complexity: "intermediate",
    useCases: ["data-science"],
    featured: false,
    trending: false,
    hot: false,
    verified: true,
    weeklyViews: 2900,
  },
  {
    id: "skill-cso",
    slug: "skill-cso",
    name: "/cso",
    tagline: "CSO mode: infrastructure-first security audit + OWASP Top 10",
    description:
      "Chief Security Officer mode. Secrets archaeology, dependency supply chain, CI/CD pipeline security, LLM/AI security, OWASP Top 10, STRIDE threat modeling, and active verification.",
    type: "skill",
    tags: ["data-ops", "audit", "owasp", "threats"],
    author: "garrytan / gstack",
    authorUrl: "https://github.com/garrytan",
    githubUrl: "https://github.com/garrytan/gstack",
    stars: 730,
    forks: 115,
    lastUpdated: "6 days ago",
    complexity: "advanced",
    useCases: ["data-ops"],
    featured: false,
    trending: false,
    hot: false,
    verified: true,
    weeklyViews: 2500,
  },
  {
    id: "skill-checkpoint",
    slug: "skill-checkpoint",
    name: "/checkpoint",
    tagline: "Save and resume working state across sessions and handoffs",
    description:
      "Save git state, decisions made, and remaining work so you can pick up exactly where you left off — even across Conductor workspace handoffs between branches.",
    type: "skill",
    tags: ["state", "session", "git", "workflow"],
    author: "garrytan / gstack",
    authorUrl: "https://github.com/garrytan",
    githubUrl: "https://github.com/garrytan/gstack",
    stars: 650,
    forks: 100,
    lastUpdated: "1 week ago",
    complexity: "beginner",
    useCases: ["python", "productivity"],
    featured: false,
    trending: false,
    hot: false,
    verified: true,
    weeklyViews: 2100,
  },
  {
    id: "skill-forge-tick",
    slug: "skill-forge-tick",
    name: "/forge-tick",
    tagline: "Multi-agent orchestration — one leader tick for the forge system",
    description:
      "Manages forge subagents for a single iteration. Drains inbox, scans task states, spawns next queued tasks, enforces budget guards. The leader persona for autonomous multi-agent development.",
    type: "skill",
    tags: ["multi-agent", "orchestration", "automation", "forge"],
    author: "harshithuppula",
    authorUrl: "https://github.com/harshithuppula",
    stars: 340,
    forks: 55,
    lastUpdated: "1 day ago",
    complexity: "advanced",
    useCases: ["python", "data-ops"],
    featured: false,
    trending: true,
    hot: true,
    verified: false,
    weeklyViews: 1400,
  },
  {
    id: "skill-brainstorming",
    slug: "skill-brainstorming",
    name: "/brainstorming",
    tagline: "Explores intent, requirements, and design before any implementation",
    description:
      "Required before any creative work. Explores user intent, requirements, and design constraints before implementation. Prevents building the wrong thing and surfaces hidden requirements.",
    type: "skill",
    tags: ["planning", "design", "requirements", "product"],
    author: "garrytan / gstack",
    authorUrl: "https://github.com/garrytan",
    githubUrl: "https://github.com/garrytan/gstack",
    stars: 580,
    forks: 90,
    lastUpdated: "1 week ago",
    complexity: "beginner",
    useCases: ["python", "productivity"],
    featured: false,
    trending: false,
    hot: false,
    verified: true,
    weeklyViews: 1900,
  },
  {
    id: "skill-weekly-review",
    slug: "skill-weekly-review",
    name: "/weekly-review",
    tagline: "Engineering retrospective with trend tracking and team stats",
    description:
      "Weekly engineering retro. Analyzes commit history, work patterns, code quality metrics with persistent history and trend tracking. Team-aware: per-person breakdown with praise and growth areas.",
    type: "skill",
    tags: ["retro", "metrics", "team", "engineering"],
    author: "garrytan / gstack",
    authorUrl: "https://github.com/garrytan",
    githubUrl: "https://github.com/garrytan/gstack",
    stars: 490,
    forks: 75,
    lastUpdated: "2 weeks ago",
    complexity: "beginner",
    useCases: ["python", "productivity"],
    featured: false,
    trending: false,
    hot: false,
    verified: true,
    weeklyViews: 1600,
  },

  // ── Agents ────────────────────────────────────────────────────────────────
  {
    id: "agent-fullstack-dev",
    slug: "agent-fullstack-dev",
    name: "Full-Stack Developer Agent",
    tagline: "Code, test, ship, iterate — the complete dev loop",
    description:
      "A complete developer loop agent. Reads requirements, designs architecture, writes code, runs tests, fixes bugs, and opens PRs. Handles frontend through backend through deployment.",
    type: "agent",
    tags: ["fullstack", "development", "automation", "loop"],
    author: "Community",
    stars: 890,
    forks: 145,
    lastUpdated: "3 days ago",
    complexity: "advanced",
    useCases: ["python"],
    featured: true,
    trending: true,
    hot: true,
    verified: false,
    weeklyViews: 3600,
  },
  {
    id: "agent-code-reviewer",
    slug: "agent-code-reviewer",
    name: "Code Review Agent",
    tagline: "Reviews PRs for bugs, security, and performance automatically",
    description:
      "Autonomous code review agent. Reviews pull requests for bugs, security vulnerabilities, performance issues, and code style. Leaves structured, actionable inline comments.",
    type: "agent",
    tags: ["code-review", "pr", "quality", "automation"],
    author: "Community",
    stars: 760,
    forks: 120,
    lastUpdated: "4 days ago",
    complexity: "intermediate",
    useCases: ["python", "data-ops"],
    featured: false,
    trending: true,
    hot: false,
    verified: false,
    weeklyViews: 2900,
  },
  {
    id: "agent-research",
    slug: "agent-research",
    name: "Research & Synthesis Agent",
    tagline: "Deep research, multi-source gathering, citation, synthesis",
    description:
      "Multi-step research agent. Defines research questions, gathers sources, extracts key information, identifies contradictions, and synthesizes into structured reports with citations.",
    type: "agent",
    tags: ["data-science", "synthesis", "productivity", "knowledge"],
    author: "Community",
    stars: 680,
    forks: 108,
    lastUpdated: "5 days ago",
    complexity: "intermediate",
    useCases: ["data-science", "productivity"],
    featured: false,
    trending: false,
    hot: false,
    verified: false,
    weeklyViews: 2400,
  },
  {
    id: "agent-security-auditor",
    slug: "agent-security-auditor",
    name: "Security Auditor Agent",
    tagline: "OWASP checks, dependency audit, threat modeling in CI",
    description:
      "Infrastructure security scanning agent. Runs OWASP checks, dependency vulnerability scans, secret detection, and threat modeling. Designed for CI/CD integration.",
    type: "agent",
    tags: ["data-ops", "audit", "owasp", "ci-cd"],
    author: "Community",
    stars: 590,
    forks: 92,
    lastUpdated: "6 days ago",
    complexity: "advanced",
    useCases: ["data-ops", "data-ops"],
    featured: false,
    trending: false,
    hot: false,
    verified: false,
    weeklyViews: 2100,
  },
  {
    id: "agent-data-pipeline",
    slug: "agent-data-pipeline",
    name: "Data Pipeline Agent",
    tagline: "Design, build, and debug data pipelines end-to-end",
    description:
      "End-to-end data pipeline agent. Analyzes data sources, designs ETL/ELT schemas, writes transformation code, validates data quality, and monitors pipeline health.",
    type: "agent",
    tags: ["data-engineering", "pipeline", "etl", "engineering"],
    author: "Community",
    stars: 450,
    forks: 72,
    lastUpdated: "1 week ago",
    complexity: "advanced",
    useCases: ["data-engineering"],
    featured: false,
    trending: false,
    hot: false,
    verified: false,
    weeklyViews: 1700,
  },
  {
    id: "agent-content-creator",
    slug: "agent-content-creator",
    name: "Content Creator Agent",
    tagline: "Research → outline → draft → edit → publish — full content lifecycle",
    description:
      "Complete content lifecycle agent. Researches topic, creates structured outline, drafts long-form content, self-edits for clarity and SEO, and prepares for publishing.",
    type: "agent",
    tags: ["productivity", "content", "seo", "publishing"],
    author: "Community",
    stars: 530,
    forks: 84,
    lastUpdated: "5 days ago",
    complexity: "intermediate",
    useCases: ["productivity"],
    featured: false,
    trending: true,
    hot: false,
    verified: false,
    weeklyViews: 2300,
  },
  {
    id: "agent-devops",
    slug: "agent-devops",
    name: "DevOps Agent",
    tagline: "CI/CD setup, infrastructure-as-code, incident response",
    description:
      "Automates the operations layer. Sets up CI/CD pipelines, writes infrastructure-as-code, manages monitoring/alerting configs, and handles incident response runbooks.",
    type: "agent",
    tags: ["data-ops", "ci-cd", "infrastructure", "monitoring"],
    author: "Community",
    stars: 490,
    forks: 78,
    lastUpdated: "1 week ago",
    complexity: "advanced",
    useCases: ["data-ops"],
    featured: false,
    trending: false,
    hot: false,
    verified: false,
    weeklyViews: 1900,
  },
  {
    id: "agent-pm",
    slug: "agent-pm",
    name: "Product Manager Agent",
    tagline: "User research → PRD → feature spec → acceptance criteria",
    description:
      "Full PM workflow agent. Gathers user research, writes PRDs with clear problem statements, breaks down features into specs with acceptance criteria, and plans sprint stories.",
    type: "agent",
    tags: ["product", "pm", "prd", "requirements"],
    author: "Community",
    stars: 420,
    forks: 66,
    lastUpdated: "2 weeks ago",
    complexity: "intermediate",
    useCases: ["productivity"],
    featured: false,
    trending: false,
    hot: false,
    verified: false,
    weeklyViews: 1600,
  },

  // ── Prompts ───────────────────────────────────────────────────────────────
  {
    id: "prompt-system-design",
    slug: "prompt-system-design",
    name: "System Design Blueprint",
    tagline: "Requirements → scale → components → data model → tradeoffs",
    description:
      "Structured system design framework. Guides Claude through requirements gathering, scale estimation, component design, data modeling, API design, and explicit tradeoff analysis.",
    type: "prompt",
    tags: ["architecture", "system-design", "interview", "backend"],
    author: "Community",
    stars: 1800,
    forks: 310,
    lastUpdated: "3 days ago",
    complexity: "intermediate",
    useCases: ["python", "data-science"],
    featured: true,
    trending: true,
    hot: true,
    verified: true,
    weeklyViews: 5800,
  },
  {
    id: "prompt-code-review",
    slug: "prompt-code-review",
    name: "Deep Code Review Template",
    tagline: "Multi-angle review: bugs, security, performance, maintainability",
    description:
      "Comprehensive code review prompt. Systematically evaluates for logic bugs, security vulnerabilities, performance bottlenecks, code maintainability, and test coverage gaps.",
    type: "prompt",
    tags: ["code-review", "quality", "data-ops", "performance"],
    author: "Community",
    stars: 1400,
    forks: 240,
    lastUpdated: "4 days ago",
    complexity: "beginner",
    useCases: ["python"],
    featured: false,
    trending: true,
    hot: false,
    verified: true,
    weeklyViews: 4200,
  },
  {
    id: "prompt-sql-optimizer",
    slug: "prompt-sql-optimizer",
    name: "SQL Query Optimizer",
    tagline: "Analyze query plans, find bottlenecks, rewrite for performance",
    description:
      "Systematic SQL optimization prompt. Analyzes execution plans, identifies index opportunities, rewrites for performance, and explains each optimization with expected impact.",
    type: "prompt",
    tags: ["sql", "performance", "database", "optimization"],
    author: "Community",
    stars: 1100,
    forks: 190,
    lastUpdated: "5 days ago",
    complexity: "intermediate",
    useCases: ["data-engineering", "python"],
    featured: false,
    trending: false,
    hot: false,
    verified: true,
    weeklyViews: 3400,
  },
  {
    id: "prompt-debug-workflow",
    slug: "prompt-debug-workflow",
    name: "Debug → Fix Pipeline",
    tagline: "Reproduce → isolate → root cause → fix → verify",
    description:
      "Structured debugging template. Forces systematic reproduction steps, minimal test case isolation, root cause identification before fix attempts, and verification protocol.",
    type: "prompt",
    tags: ["debugging", "bugs", "workflow", "systematic"],
    author: "Community",
    stars: 1300,
    forks: 220,
    lastUpdated: "4 days ago",
    complexity: "beginner",
    useCases: ["python"],
    featured: false,
    trending: false,
    hot: false,
    verified: true,
    weeklyViews: 3800,
  },
  {
    id: "prompt-adr",
    slug: "prompt-adr",
    name: "Architecture Decision Record",
    tagline: "Structured ADR: context, options, decision, consequences",
    description:
      "Full ADR template. Captures architectural context, decision drivers, all options considered with pros/cons, the chosen decision with rationale, and positive/negative consequences.",
    type: "prompt",
    tags: ["architecture", "adr", "documentation", "decisions"],
    author: "Community",
    stars: 960,
    forks: 160,
    lastUpdated: "1 week ago",
    complexity: "beginner",
    useCases: ["python"],
    featured: false,
    trending: false,
    hot: false,
    verified: true,
    weeklyViews: 2900,
  },
  {
    id: "prompt-api-docs",
    slug: "prompt-api-docs",
    name: "API Documentation Generator",
    tagline: "Endpoint spec, examples, error codes, SDK usage from code",
    description:
      "Generate structured API documentation from code. Produces endpoint specs with request/response schemas, example calls in multiple languages, error codes, and usage patterns.",
    type: "prompt",
    tags: ["api", "documentation", "openapi", "developer"],
    author: "Community",
    stars: 870,
    forks: 140,
    lastUpdated: "1 week ago",
    complexity: "beginner",
    useCases: ["python"],
    featured: false,
    trending: true,
    hot: false,
    verified: false,
    weeklyViews: 2700,
  },
  {
    id: "prompt-ml-experiment",
    slug: "prompt-ml-experiment",
    name: "ML Experiment Logger",
    tagline: "Track hypothesis, dataset, model, hyperparams, results",
    description:
      "Structured ML experiment tracking template. Records hypothesis, dataset description, model architecture, hyperparameters, results metrics, and experiment learnings for reproducibility.",
    type: "prompt",
    tags: ["ml", "experiments", "reproducibility", "data-science"],
    author: "Community",
    stars: 720,
    forks: 115,
    lastUpdated: "2 weeks ago",
    complexity: "intermediate",
    useCases: ["ml-engineering", "data-engineering"],
    featured: false,
    trending: false,
    hot: false,
    verified: false,
    weeklyViews: 2100,
  },
  {
    id: "prompt-security-audit",
    slug: "prompt-security-audit",
    name: "Security Audit Checklist",
    tagline: "OWASP Top 10, injection, auth, crypto — systematic review",
    description:
      "Comprehensive security audit prompt. Walks Claude through OWASP Top 10 checks, injection vulnerabilities, authentication/authorization issues, cryptography weaknesses, and security headers.",
    type: "prompt",
    tags: ["data-ops", "owasp", "audit", "checklist"],
    author: "Community",
    stars: 890,
    forks: 145,
    lastUpdated: "6 days ago",
    complexity: "advanced",
    useCases: ["data-ops"],
    featured: false,
    trending: false,
    hot: false,
    verified: true,
    weeklyViews: 2600,
  },
  {
    id: "prompt-prd",
    slug: "prompt-prd",
    name: "Product Requirements Document",
    tagline: "Problem statement, personas, metrics, requirements, risks",
    description:
      "Full PRD template. Structures the problem statement, user personas, success metrics, functional and non-functional requirements, known risks, and out-of-scope clarifications.",
    type: "prompt",
    tags: ["product", "prd", "requirements", "planning"],
    author: "Community",
    stars: 1050,
    forks: 175,
    lastUpdated: "5 days ago",
    complexity: "beginner",
    useCases: ["productivity"],
    featured: false,
    trending: true,
    hot: false,
    verified: true,
    weeklyViews: 3200,
  },
  {
    id: "prompt-content-strategy",
    slug: "prompt-content-strategy",
    name: "Content Strategy Brief",
    tagline: "Audience, message architecture, content pillars, KPIs",
    description:
      "Strategic content planning prompt. Defines target audience segments, message architecture, content pillars, distribution channels, editorial calendar, and measurement KPIs.",
    type: "prompt",
    tags: ["content", "marketing", "strategy", "productivity"],
    author: "Community",
    stars: 780,
    forks: 125,
    lastUpdated: "1 week ago",
    complexity: "intermediate",
    useCases: ["productivity"],
    featured: false,
    trending: false,
    hot: false,
    verified: false,
    weeklyViews: 2300,
  },

  // ── Architectures ─────────────────────────────────────────────────────────
  {
    id: "arch-manager-worker",
    slug: "arch-manager-worker",
    name: "Manager-Worker Pattern",
    tagline: "One manager decomposes tasks, N workers execute in parallel",
    description:
      "Classic multi-agent architecture. A manager agent breaks down complex goals into independent subtasks, spawns specialized worker agents, and synthesizes results into a coherent output.",
    type: "architecture",
    tags: ["multi-agent", "parallel", "orchestration", "pattern"],
    author: "Community",
    stars: 890,
    forks: 145,
    lastUpdated: "3 days ago",
    complexity: "advanced",
    useCases: ["python", "ml-engineering"],
    featured: true,
    trending: true,
    hot: false,
    verified: true,
    weeklyViews: 3700,
  },
  {
    id: "arch-sequential-review",
    slug: "arch-sequential-review",
    name: "Sequential Review Chain",
    tagline: "Builder → Critic → Refiner loop for high-quality output",
    description:
      "Each agent improves the previous agent's output. Builder creates, Critic finds flaws, Refiner incorporates feedback. Iterate until quality threshold is met or iteration limit is reached.",
    type: "architecture",
    tags: ["review", "quality", "iteration", "agents"],
    author: "Community",
    stars: 740,
    forks: 118,
    lastUpdated: "4 days ago",
    complexity: "intermediate",
    useCases: ["python", "productivity"],
    featured: false,
    trending: false,
    hot: false,
    verified: false,
    weeklyViews: 2800,
  },
  {
    id: "arch-parallel-spec",
    slug: "arch-parallel-spec",
    name: "Parallel Specialization",
    tagline: "Multiple specialists work simultaneously, leader merges",
    description:
      "Multiple specialized agents work on different aspects of a problem in parallel. Frontend agent, backend agent, security agent, and docs agent all run concurrently. Leader merges results.",
    type: "architecture",
    tags: ["parallel", "specialization", "concurrency", "agents"],
    author: "Community",
    stars: 680,
    forks: 108,
    lastUpdated: "5 days ago",
    complexity: "advanced",
    useCases: ["python"],
    featured: false,
    trending: false,
    hot: false,
    verified: false,
    weeklyViews: 2500,
  },
  {
    id: "arch-debate",
    slug: "arch-debate",
    name: "Debate & Arbitration",
    tagline: "Two agents argue opposing positions, a third arbitrates",
    description:
      "Two agents argue opposing positions on a design decision or analysis. A third arbitrator evaluates the arguments and makes a final recommendation. Best for complex tradeoff decisions.",
    type: "architecture",
    tags: ["debate", "tradeoffs", "decision-making", "adversarial"],
    author: "Community",
    stars: 590,
    forks: 94,
    lastUpdated: "6 days ago",
    complexity: "advanced",
    useCases: ["data-science", "ml-engineering"],
    featured: false,
    trending: true,
    hot: false,
    verified: false,
    weeklyViews: 2200,
  },
  {
    id: "arch-event-driven",
    slug: "arch-event-driven",
    name: "Event-Driven Agents",
    tagline: "Agents respond to system events — file changes, webhooks, APIs",
    description:
      "Agents triggered by external events rather than direct invocation. File changes, API calls, webhooks, and cron schedules fire agent chains. The backbone of autonomous AI workflows.",
    type: "architecture",
    tags: ["events", "webhooks", "autonomous", "workflow"],
    author: "Community",
    stars: 510,
    forks: 82,
    lastUpdated: "1 week ago",
    complexity: "advanced",
    useCases: ["data-ops", "python"],
    featured: false,
    trending: false,
    hot: false,
    verified: false,
    weeklyViews: 1900,
  },
  {
    id: "arch-rag-pipeline",
    slug: "arch-rag-pipeline",
    name: "RAG Pipeline Architecture",
    tagline: "Embedding pipeline, vector search, context injection",
    description:
      "Retrieval-Augmented Generation architecture. Embedding pipeline ingests documents, vector store enables semantic search, retriever pulls relevant context, generator produces grounded output.",
    type: "architecture",
    tags: ["rag", "embeddings", "vector-search", "llm"],
    author: "Community",
    stars: 820,
    forks: 132,
    lastUpdated: "2 days ago",
    complexity: "advanced",
    useCases: ["ml-engineering", "data-science"],
    featured: false,
    trending: true,
    hot: true,
    verified: true,
    weeklyViews: 3400,
  },

  // ── Setups ────────────────────────────────────────────────────────────────
  {
    id: "setup-minimal-coding",
    slug: "setup-minimal-coding",
    name: "Minimal Coding Setup",
    tagline: "Filesystem + GitHub MCPs — the essential stack",
    description:
      "The minimal effective Claude coding setup. Filesystem MCP for local file access, GitHub MCP for version control, and Claude Code CLI with basic CLAUDE.md. Works for any project.",
    type: "setup",
    tags: ["setup", "minimal", "github", "filesystem"],
    author: "Community",
    stars: 1200,
    forks: 200,
    lastUpdated: "3 days ago",
    complexity: "beginner",
    useCases: ["python"],
    featured: true,
    trending: true,
    hot: false,
    verified: true,
    weeklyViews: 4800,
  },
  {
    id: "setup-fullstack-dev",
    slug: "setup-fullstack-dev",
    name: "Full-Stack Dev Setup",
    tagline: "Postgres + GitHub + Vercel + filesystem — ship end-to-end",
    description:
      "Complete full-stack development environment. PostgreSQL MCP for database access, GitHub for version control, Vercel for deployment, filesystem for local editing. Ship entire features from Claude.",
    type: "setup",
    tags: ["fullstack", "postgres", "vercel", "complete"],
    author: "Community",
    stars: 980,
    forks: 160,
    lastUpdated: "4 days ago",
    complexity: "intermediate",
    useCases: ["python", "data-ops"],
    featured: false,
    trending: true,
    hot: true,
    verified: true,
    weeklyViews: 3900,
  },
  {
    id: "setup-research-engine",
    slug: "setup-research-engine",
    name: "Research Engine Setup",
    tagline: "Brave Search + Notion + filesystem — deep research stack",
    description:
      "Complete research environment. Brave Search for web access, Notion for knowledge management, filesystem for local notes, and deep research skills. For analysts, researchers, and writers.",
    type: "setup",
    tags: ["data-science", "search", "notion", "knowledge"],
    author: "Community",
    stars: 760,
    forks: 122,
    lastUpdated: "5 days ago",
    complexity: "beginner",
    useCases: ["data-science", "productivity"],
    featured: false,
    trending: false,
    hot: false,
    verified: false,
    weeklyViews: 2700,
  },
  {
    id: "setup-data-stack",
    slug: "setup-data-stack",
    name: "Data Engineering Setup",
    tagline: "Postgres + S3 + GitHub — full data pipeline management",
    description:
      "Complete data engineering environment. PostgreSQL for warehouse access, S3 for data lake operations, GitHub for pipeline version control, and data-specific prompt templates.",
    type: "setup",
    tags: ["data-engineering", "postgres", "s3", "pipeline"],
    author: "Community",
    stars: 640,
    forks: 103,
    lastUpdated: "1 week ago",
    complexity: "intermediate",
    useCases: ["data-engineering"],
    featured: false,
    trending: false,
    hot: false,
    verified: false,
    weeklyViews: 2100,
  },
  {
    id: "setup-security-toolkit",
    slug: "setup-security-toolkit",
    name: "Security Researcher Setup",
    tagline: "Filesystem + Docker + Brave Search — security research stack",
    description:
      "Security research environment. Filesystem for code analysis, Docker MCP for isolated testing environments, Brave Search for vulnerability research, and security-focused skill set.",
    type: "setup",
    tags: ["data-ops", "data-science", "docker", "audit"],
    author: "Community",
    stars: 580,
    forks: 92,
    lastUpdated: "2 weeks ago",
    complexity: "advanced",
    useCases: ["data-ops"],
    featured: false,
    trending: false,
    hot: false,
    verified: false,
    weeklyViews: 1800,
  },

  // ── Hooks ─────────────────────────────────────────────────────────────────
  {
    id: "hook-auto-format",
    slug: "hook-auto-format",
    name: "Auto-Formatter Hook",
    tagline: "Run Prettier or Black automatically after every file edit",
    description:
      "PostToolUse hook that runs a formatter after every file write. Configurable per language — Prettier for JS/TS, Black for Python, gofmt for Go. Keeps code style consistent without manual runs.",
    type: "hook",
    tags: ["formatter", "prettier", "black", "automation"],
    author: "Community",
    stars: 920,
    forks: 148,
    lastUpdated: "2 days ago",
    complexity: "beginner",
    useCases: ["python"],
    featured: true,
    trending: true,
    hot: true,
    verified: true,
    weeklyViews: 4200,
  },
  {
    id: "hook-test-runner",
    slug: "hook-test-runner",
    name: "Test Runner Hook",
    tagline: "Auto-run tests after code changes and surface failures instantly",
    description:
      "PostToolUse hook that runs your test suite after every relevant code change. Surfaces failures immediately so Claude can fix them in the same context. Supports Jest, pytest, Vitest, and more.",
    type: "hook",
    tags: ["testing", "ci", "automation", "tdd"],
    author: "Community",
    stars: 780,
    forks: 125,
    lastUpdated: "3 days ago",
    complexity: "intermediate",
    useCases: ["python"],
    featured: false,
    trending: true,
    hot: false,
    verified: true,
    weeklyViews: 3300,
  },
  {
    id: "hook-security-scanner",
    slug: "hook-security-scanner",
    name: "Security Scanner Hook",
    tagline: "Scan for secrets and vulnerabilities before any git commit",
    description:
      "PreToolUse hook on Bash that intercepts git commits and scans staged files for secrets, hardcoded credentials, and known vulnerability patterns. Blocks commits with critical findings.",
    type: "hook",
    tags: ["data-ops", "git", "secrets", "scanning"],
    author: "Community",
    stars: 690,
    forks: 110,
    lastUpdated: "4 days ago",
    complexity: "intermediate",
    useCases: ["data-ops", "data-ops"],
    featured: false,
    trending: true,
    hot: false,
    verified: false,
    weeklyViews: 2800,
  },
  {
    id: "hook-notification",
    slug: "hook-notification",
    name: "Completion Notification Hook",
    tagline: "Slack or macOS notification when Claude finishes a long task",
    description:
      "Stop/notification hook that fires when Claude completes a task. Sends a macOS notification, Slack message, or email. Useful for long builds, deployments, or overnight tasks.",
    type: "hook",
    tags: ["notifications", "slack", "productivity", "async"],
    author: "Community",
    stars: 560,
    forks: 89,
    lastUpdated: "5 days ago",
    complexity: "beginner",
    useCases: ["productivity"],
    featured: false,
    trending: false,
    hot: true,
    verified: false,
    weeklyViews: 2400,
  },
  {
    id: "hook-linter",
    slug: "hook-linter",
    name: "Linter Hook",
    tagline: "ESLint or Pylint runs on save, errors fed back to Claude",
    description:
      "PostToolUse hook that runs a linter after each file edit and pipes the output directly into Claude's context. Claude sees lint errors in real time and fixes them before moving on.",
    type: "hook",
    tags: ["linting", "eslint", "pylint", "code-quality"],
    author: "Community",
    stars: 630,
    forks: 100,
    lastUpdated: "6 days ago",
    complexity: "beginner",
    useCases: ["python"],
    featured: false,
    trending: false,
    hot: false,
    verified: true,
    weeklyViews: 2100,
  },

  // ── Tricks ────────────────────────────────────────────────────────────────
  {
    id: "trick-extended-thinking",
    slug: "trick-extended-thinking",
    name: "Extended Thinking Mode",
    tagline: "Unlock Claude's deep reasoning for hard architectural problems",
    description:
      "Enable extended thinking via --thinking-budget flag in Claude Code. Use for complex architectural decisions, algorithm design, debugging hard edge cases. Trades speed for depth.",
    type: "trick",
    tags: ["thinking", "reasoning", "architecture", "advanced"],
    author: "Community",
    stars: 2100,
    forks: 380,
    lastUpdated: "1 day ago",
    complexity: "beginner",
    useCases: ["python", "ml-engineering"],
    featured: true,
    trending: true,
    hot: true,
    verified: true,
    weeklyViews: 7200,
  },
  {
    id: "trick-parallel-agents",
    slug: "trick-parallel-agents",
    name: "Parallel Agent Spawning",
    tagline: "Multiple Claude sessions on separate worktrees — true parallelism",
    description:
      "Spawn multiple Claude Code sessions in separate git worktrees. Each handles an independent task simultaneously. 4x throughput for multi-feature sprints. Core forge architecture pattern.",
    type: "trick",
    tags: ["parallel", "worktrees", "performance", "multi-agent"],
    author: "Community",
    stars: 1400,
    forks: 240,
    lastUpdated: "2 days ago",
    complexity: "advanced",
    useCases: ["python"],
    featured: true,
    trending: true,
    hot: true,
    verified: true,
    weeklyViews: 5800,
  },
  {
    id: "trick-prompt-caching",
    slug: "trick-prompt-caching",
    name: "Prompt Caching for 90% Cost Reduction",
    tagline: "Cache system prompts and large docs to slash API costs",
    description:
      "Use cache_control: ephemeral on system prompts, large codebases, and documents. Claude caches the prefix and charges 10% of the normal rate on cache hits. Essential for production.",
    type: "trick",
    tags: ["caching", "cost", "api", "performance"],
    author: "Community",
    stars: 1700,
    forks: 295,
    lastUpdated: "3 days ago",
    complexity: "intermediate",
    useCases: ["python", "ml-engineering"],
    featured: false,
    trending: true,
    hot: true,
    verified: true,
    weeklyViews: 6100,
  },
  {
    id: "trick-ci-claude",
    slug: "trick-ci-claude",
    name: "Claude in CI/CD Pipelines",
    tagline: "Non-interactive Claude in GitHub Actions — auto-review and fix",
    description:
      "Run Claude as a non-interactive step in GitHub Actions. Auto-review PRs, fix lint errors, update changelogs, generate release notes, and run custom validations on every commit.",
    type: "trick",
    tags: ["ci-cd", "github-actions", "automation", "data-ops"],
    author: "Community",
    stars: 1100,
    forks: 185,
    lastUpdated: "4 days ago",
    complexity: "intermediate",
    useCases: ["data-ops", "python"],
    featured: false,
    trending: true,
    hot: false,
    verified: true,
    weeklyViews: 4300,
  },
  {
    id: "trick-custom-commands",
    slug: "trick-custom-commands",
    name: "Writing Custom Slash Commands",
    tagline: "Build your own SKILL.md files and register as /commands",
    description:
      "Write custom slash commands as SKILL.md files and drop them in .claude/skills/. Claude Code picks them up as /commands. Build team-specific workflows that fit your stack.",
    type: "trick",
    tags: ["skills", "customization", "workflow", "commands"],
    author: "Community",
    stars: 890,
    forks: 145,
    lastUpdated: "5 days ago",
    complexity: "beginner",
    useCases: ["python", "productivity"],
    featured: false,
    trending: false,
    hot: false,
    verified: true,
    weeklyViews: 3500,
  },

  // ── Data Stack Resources ──────────────────────────────────────────────────
  {
    id: "kafka-mcp",
    slug: "kafka-mcp",
    name: "Apache Kafka MCP",
    tagline: "Stream data in real-time with Claude",
    description:
      "Connect Claude to Apache Kafka topics. Read, produce, and analyze streaming messages. Ideal for monitoring pipeline health, debugging consumer lag, and understanding event schemas in real time.",
    type: "mcp",
    tags: ["kafka", "streaming", "real-time", "data-engineering"],
    author: "confluentinc",
    githubUrl: "https://github.com/confluentinc/kafka-mcp",
    installCommand: "claude mcp add kafka-mcp",
    stars: 1340,
    forks: 187,
    lastUpdated: "2026-04-12",
    complexity: "intermediate",
    useCases: ["data-engineering", "data-ops"],
    featured: false,
    trending: true,
    hot: false,
    verified: true,
    weeklyViews: 3200,
  },
  {
    id: "spark-mcp",
    slug: "spark-mcp",
    name: "Apache Spark MCP",
    tagline: "Query and monitor Spark jobs with Claude",
    description:
      "Interact with Apache Spark clusters via Claude. Submit jobs, query DataFrames, monitor stages, and get intelligent recommendations for performance tuning. Works with Databricks and standalone Spark.",
    type: "mcp",
    tags: ["spark", "big-data", "distributed", "databricks"],
    author: "apache-community",
    githubUrl: "https://github.com/apache-community/spark-mcp",
    installCommand: "claude mcp add spark-mcp",
    stars: 980,
    forks: 134,
    lastUpdated: "2026-03-28",
    complexity: "advanced",
    useCases: ["data-engineering", "data-science"],
    featured: false,
    trending: false,
    hot: true,
    verified: false,
    weeklyViews: 2100,
  },
  {
    id: "dbt-cloud-mcp",
    slug: "dbt-cloud-mcp",
    name: "dbt Cloud MCP",
    tagline: "Run, test, and document your dbt models",
    description:
      "Connect Claude to dbt Cloud. Trigger runs, inspect model DAGs, read test results, and generate documentation. Claude can suggest model optimizations and help debug failing tests.",
    type: "mcp",
    tags: ["dbt", "data-modeling", "sql", "analytics-engineering"],
    author: "dbt-labs",
    githubUrl: "https://github.com/dbt-labs/dbt-mcp",
    installCommand: "claude mcp add dbt-cloud-mcp",
    stars: 2300,
    forks: 312,
    lastUpdated: "2026-05-01",
    complexity: "intermediate",
    useCases: ["data-engineering", "analytics", "sql"],
    featured: true,
    trending: true,
    hot: true,
    verified: true,
    weeklyViews: 5800,
  },
  {
    id: "airflow-mcp",
    slug: "airflow-mcp",
    name: "Apache Airflow MCP",
    tagline: "Manage DAGs and debug pipeline failures",
    description:
      "Interact with Apache Airflow via Claude. List DAGs, trigger runs, inspect task logs, and get AI-powered root cause analysis for failed tasks. Supports Airflow 2.x and MWAA.",
    type: "mcp",
    tags: ["airflow", "orchestration", "pipeline", "dag"],
    author: "apache-community",
    githubUrl: "https://github.com/apache-community/airflow-mcp",
    installCommand: "claude mcp add airflow-mcp",
    stars: 1760,
    forks: 223,
    lastUpdated: "2026-04-20",
    complexity: "intermediate",
    useCases: ["data-engineering", "data-ops"],
    featured: false,
    trending: true,
    hot: false,
    verified: true,
    weeklyViews: 4100,
  },
  {
    id: "snowflake-mcp",
    slug: "snowflake-mcp",
    name: "Snowflake MCP",
    tagline: "Query Snowflake warehouses in plain English",
    description:
      "Connect Claude to Snowflake. Run SQL queries, inspect schemas, analyze query history, and optimize warehouse usage. Claude can translate natural language questions into optimized Snowflake SQL.",
    type: "mcp",
    tags: ["snowflake", "sql", "cloud-warehouse", "analytics"],
    author: "snowflake-labs",
    githubUrl: "https://github.com/snowflake-labs/snowflake-mcp",
    installCommand: "claude mcp add snowflake-mcp",
    stars: 3100,
    forks: 421,
    lastUpdated: "2026-05-05",
    complexity: "beginner",
    useCases: ["analytics", "sql", "data-engineering"],
    featured: true,
    trending: true,
    hot: true,
    verified: true,
    weeklyViews: 7200,
  },
  {
    id: "bigquery-mcp",
    slug: "bigquery-mcp",
    name: "BigQuery MCP",
    tagline: "Analyze petabytes with Claude on BigQuery",
    description:
      "Let Claude query Google BigQuery directly. Supports standard SQL, partition pruning advice, cost estimation, and schema exploration. Works with BigQuery ML for in-database model training.",
    type: "mcp",
    tags: ["bigquery", "gcp", "sql", "analytics"],
    author: "googleapis",
    githubUrl: "https://github.com/googleapis/bigquery-mcp",
    installCommand: "claude mcp add bigquery-mcp",
    stars: 2650,
    forks: 347,
    lastUpdated: "2026-04-30",
    complexity: "beginner",
    useCases: ["analytics", "sql", "data-science"],
    featured: true,
    trending: true,
    hot: false,
    verified: true,
    weeklyViews: 6300,
  },
  {
    id: "delta-lake-mcp",
    slug: "delta-lake-mcp",
    name: "Delta Lake MCP",
    tagline: "Time-travel and ACID transactions with Claude",
    description:
      "Interact with Delta Lake tables via Claude. Query historical versions, run VACUUM, inspect transaction logs, and optimize file layout. Works with Databricks, OSS Delta, and Unity Catalog.",
    type: "mcp",
    tags: ["delta-lake", "databricks", "lakehouse", "spark"],
    author: "delta-io",
    githubUrl: "https://github.com/delta-io/delta-mcp",
    installCommand: "claude mcp add delta-lake-mcp",
    stars: 1420,
    forks: 198,
    lastUpdated: "2026-04-15",
    complexity: "advanced",
    useCases: ["data-engineering", "data-science"],
    featured: false,
    trending: false,
    hot: true,
    verified: true,
    weeklyViews: 2800,
  },
  {
    id: "dbt-debug-skill",
    slug: "dbt-debug-skill",
    name: "/dbt-debug",
    tagline: "Root-cause dbt model failures in seconds",
    description:
      "Paste a dbt error and Claude will trace through the DAG, identify the failing node, check upstream dependencies, and suggest the exact fix — whether it's a bad join, a missing source, or a Jinja rendering error.",
    type: "skill",
    tags: ["dbt", "debugging", "sql", "analytics-engineering"],
    author: "dbt-community",
    githubUrl: "https://github.com/dbt-community/claude-skills",
    installCommand: "claude skills add dbt-debug",
    stars: 890,
    forks: 112,
    lastUpdated: "2026-04-08",
    complexity: "intermediate",
    useCases: ["data-engineering", "sql"],
    featured: false,
    trending: true,
    hot: false,
    verified: false,
    weeklyViews: 2900,
  },
  {
    id: "sql-optimize-skill",
    slug: "sql-optimize-skill",
    name: "/sql-optimize",
    tagline: "Rewrite slow SQL queries for maximum speed",
    description:
      "Paste any SQL query and Claude analyzes it for N+1 patterns, missing indexes, cartesian joins, and suboptimal aggregations. Returns a rewritten query with an explanation of every change and expected speedup.",
    type: "skill",
    tags: ["sql", "performance", "query-optimization", "analytics"],
    author: "sqltools-community",
    githubUrl: "https://github.com/sqltools-community/claude-skills",
    installCommand: "claude skills add sql-optimize",
    stars: 1540,
    forks: 201,
    lastUpdated: "2026-05-02",
    complexity: "intermediate",
    useCases: ["sql", "analytics", "data-engineering"],
    featured: true,
    trending: true,
    hot: true,
    verified: true,
    weeklyViews: 4700,
  },
  {
    id: "data-quality-skill",
    slug: "data-quality-skill",
    name: "/data-quality",
    tagline: "Generate dbt tests and Great Expectations suites",
    description:
      "Describe your dataset and Claude generates a full data quality suite — dbt schema tests, Great Expectations checkpoints, or Soda checks. Covers nulls, uniqueness, referential integrity, and statistical anomalies.",
    type: "skill",
    tags: ["data-quality", "testing", "dbt", "great-expectations"],
    author: "data-reliability-eng",
    githubUrl: "https://github.com/data-reliability-eng/claude-skills",
    installCommand: "claude skills add data-quality",
    stars: 720,
    forks: 98,
    lastUpdated: "2026-03-20",
    complexity: "intermediate",
    useCases: ["data-engineering", "analytics", "data-ops"],
    featured: false,
    trending: false,
    hot: false,
    verified: false,
    weeklyViews: 1800,
  },
  {
    id: "pipeline-monitor-agent",
    slug: "pipeline-monitor-agent",
    name: "Pipeline Monitor Agent",
    tagline: "24/7 autonomous data pipeline watchdog",
    description:
      "An autonomous Claude agent that monitors Airflow/Prefect/Dagster pipelines. Detects failures, analyzes logs, traces upstream root causes, posts Slack alerts with actionable summaries, and optionally retries idempotent tasks.",
    type: "agent",
    tags: ["monitoring", "airflow", "alerting", "data-ops"],
    author: "dataops-community",
    githubUrl: "https://github.com/dataops-community/pipeline-monitor-agent",
    stars: 1100,
    forks: 145,
    lastUpdated: "2026-04-25",
    complexity: "advanced",
    useCases: ["data-ops", "data-engineering"],
    featured: true,
    trending: true,
    hot: true,
    verified: false,
    weeklyViews: 3600,
  },
  {
    id: "schema-drift-agent",
    slug: "schema-drift-agent",
    name: "Schema Drift Detector",
    tagline: "Catch breaking schema changes before they break pipelines",
    description:
      "Continuously compares source and destination schemas. When drift is detected, Claude generates a migration script, identifies downstream models at risk, and opens a GitHub issue with impact analysis.",
    type: "agent",
    tags: ["schema", "data-quality", "migration", "dbt"],
    author: "data-contracts-io",
    githubUrl: "https://github.com/data-contracts-io/schema-drift-agent",
    stars: 840,
    forks: 107,
    lastUpdated: "2026-04-10",
    complexity: "advanced",
    useCases: ["data-engineering", "data-ops"],
    featured: false,
    trending: true,
    hot: false,
    verified: false,
    weeklyViews: 2200,
  },
  {
    id: "nl-to-sql-prompt",
    slug: "nl-to-sql-prompt",
    name: "NL to SQL Master Prompt",
    tagline: "Turn any business question into production-ready SQL",
    description:
      "A carefully engineered prompt that transforms natural language business questions into optimized SQL. Handles complex joins, window functions, CTEs, and dialect-specific syntax for Snowflake, BigQuery, Redshift, and Postgres.",
    type: "prompt",
    tags: ["sql", "natural-language", "analytics", "llm"],
    author: "prompt-engineers-guild",
    githubUrl: "https://github.com/prompt-engineers-guild/data-prompts",
    stars: 2800,
    forks: 390,
    lastUpdated: "2026-05-03",
    complexity: "beginner",
    useCases: ["sql", "analytics", "data-science"],
    featured: true,
    trending: true,
    hot: true,
    verified: true,
    weeklyViews: 8100,
  },
  {
    id: "pipeline-design-prompt",
    slug: "pipeline-design-prompt",
    name: "Data Pipeline Design Prompt",
    tagline: "Design production-grade pipelines from requirements",
    description:
      "Feed Claude your data sources, SLAs, and business requirements. This prompt guides Claude to produce a full pipeline design: ingestion layer, transformation logic, storage strategy, orchestration DAG skeleton, and monitoring plan.",
    type: "prompt",
    tags: ["pipeline", "architecture", "design", "data-engineering"],
    author: "data-architects-club",
    githubUrl: "https://github.com/data-architects-club/prompts",
    stars: 1340,
    forks: 178,
    lastUpdated: "2026-04-18",
    complexity: "intermediate",
    useCases: ["data-engineering", "analytics"],
    featured: false,
    trending: false,
    hot: false,
    verified: false,
    weeklyViews: 2400,
  },
  {
    id: "data-profiling-trick",
    slug: "data-profiling-trick",
    name: "Data Profiling with Claude",
    tagline: "Profile any dataset in under 60 seconds",
    description:
      "Paste a CSV sample or schema into Claude with this trick: ask it to produce a full data profile — cardinality, null rates, value distributions, outliers, and data type recommendations. Pair with the Postgres or BigQuery MCP for live profiling.",
    type: "trick",
    tags: ["data-profiling", "analytics", "eda", "python"],
    author: "eda-tricks",
    githubUrl: "https://github.com/eda-tricks/claude-data-tricks",
    stars: 670,
    forks: 89,
    lastUpdated: "2026-03-15",
    complexity: "beginner",
    useCases: ["data-science", "analytics"],
    featured: false,
    trending: false,
    hot: false,
    verified: false,
    weeklyViews: 1600,
  },
  {
    id: "medallion-arch",
    slug: "medallion-arch",
    name: "Medallion Architecture with Claude",
    tagline: "Bronze → Silver → Gold pipeline pattern with AI quality gates",
    description:
      "A complete multi-agent architecture for medallion lakehouses. Claude agents handle Bronze ingestion validation, Silver transformation QA, and Gold business logic verification. Each layer has its own agent persona with specialized tools.",
    type: "architecture",
    tags: ["medallion", "lakehouse", "delta-lake", "databricks"],
    author: "lakehouse-patterns",
    githubUrl: "https://github.com/lakehouse-patterns/medallion-claude",
    stars: 920,
    forks: 124,
    lastUpdated: "2026-04-22",
    complexity: "advanced",
    useCases: ["data-engineering", "data-ops"],
    featured: true,
    trending: true,
    hot: false,
    verified: false,
    weeklyViews: 2900,
  },
  {
    id: "data-engineer-setup",
    slug: "data-engineer-setup",
    name: "Data Engineer Claude Setup",
    tagline: "The complete Claude environment for data engineers",
    description:
      "A curated CLAUDE.md, MCP stack (Postgres + dbt + Airflow + GitHub), and skill set for data engineers. Includes custom personas for pipeline debugging, SQL review, and incident response. Tested on macOS and Linux.",
    type: "setup",
    tags: ["setup", "data-engineering", "mcp", "claude-code"],
    author: "de-setups",
    githubUrl: "https://github.com/de-setups/claude-data-engineer",
    installCommand: "curl -sSL https://de-setups.sh | bash",
    stars: 1680,
    forks: 234,
    lastUpdated: "2026-05-06",
    complexity: "intermediate",
    useCases: ["data-engineering", "productivity"],
    featured: true,
    trending: true,
    hot: true,
    verified: true,
    weeklyViews: 4200,
  },
  {
    id: "data-validation-hook",
    slug: "data-validation-hook",
    name: "Pre-commit Data Validation Hook",
    tagline: "Validate dbt models and SQL before every commit",
    description:
      "A Claude Code hook that runs on pre-commit. Automatically lints SQL files, checks dbt model references, validates schema.yml consistency, and blocks commits with broken upstream dependencies or missing tests.",
    type: "hook",
    tags: ["pre-commit", "dbt", "sql", "data-quality"],
    author: "data-hooks-io",
    githubUrl: "https://github.com/data-hooks-io/precommit-data",
    installCommand: "claude hooks add data-validation",
    stars: 560,
    forks: 72,
    lastUpdated: "2026-04-05",
    complexity: "intermediate",
    useCases: ["data-engineering", "data-ops"],
    featured: false,
    trending: false,
    hot: false,
    verified: false,
    weeklyViews: 1400,
  },
];

// ── Helpers ───────────────────────────────────────────────────────────────

export function getByType(type: string) {
  return resources.filter((r) => r.type === type);
}

export function getBySlug(slug: string) {
  return resources.find((r) => r.slug === slug);
}

export function getFeatured() {
  return resources.filter((r) => r.featured);
}

export function getTrending() {
  return [...resources]
    .filter((r) => r.trending)
    .sort((a, b) => b.weeklyViews - a.weeklyViews);
}

export function getHot() {
  return [...resources]
    .filter((r) => r.hot)
    .sort((a, b) => b.weeklyViews - a.weeklyViews);
}

export function getNew() {
  return [...resources].slice().reverse();
}

export function getTop() {
  return [...resources].sort((a, b) => b.stars - a.stars);
}

export function getRelated(resource: Resource, limit = 4) {
  return resources
    .filter(
      (r) =>
        r.id !== resource.id &&
        (r.type === resource.type ||
          r.tags.some((t) => resource.tags.includes(t)))
    )
    .sort((a, b) => b.stars - a.stars)
    .slice(0, limit);
}

export function getCounts() {
  const counts: Record<string, number> = {};
  for (const r of resources) {
    counts[r.type] = (counts[r.type] || 0) + 1;
  }
  return counts;
}

export const RESOURCES = resources;
